@startuml
'https://plantuml.com/sequence-diagram

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Search for a specific professional (SSD)

autonumber

actor Refugee
participant ":System" as System

activate Refugee
    Refugee -> System : starts the process of searching for the services provided by a specific professional
    activate System
        System --> Refugee : requests professional information(name)
    deactivate System

    Refugee -> System : fills the requested data
    activate System
        System --> Refugee : shows all the services provided by a specific professional, ordered by geographic proximity, validates and asks for confirmation
    deactivate System

    Refugee -> System : confirms
    activate System
        System --> Refugee : notifies the success of the operation
    deactivate System
deactivate Refugee
@enduml