@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Choose the application language

autonumber

actor SystemUser

participant "ChooseLanguageUI" as ui

activate SystemUser
    SystemUser -> ui : starts the process of choose a language
    activate ui
        ui --> SystemUser: displays a list of languages
    deactivate ui
    SystemUser -> ui : selects a language
    activate ui
        ui --> SystemUser : refresh page and displays a page translated version
    deactivate ui
deactivate SystemUser

@enduml