@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UC008 - System Sequence Diagram (SSD)

autonumber

actor Refugee
participant ":System" as System

activate Refugee
    Refugee -> System : starts the process of rating an appointment
    activate System
        System --> Refugee : shows a list of previous services
    deactivate System

    Refugee -> System : choose a previous service to evaluate

    activate System
        System --> Refugee : displays the service details and shows a rating scale from 1 to 5
    deactivate System
    Refugee -> System : rate the service provider and write a short message (optional)

    activate System
        System --> Refugee: records the information and shows a possible rating edition;
deactivate Refugee

@enduml