@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title UC025 - View a list of donations I made.

class Donation {
    Id
    Value
    Donation Type
    Date
    Payment Method
}

class Donor {
    Id
    First Name
    Last Name
    Address
    NIF/NIPC
    Email
    Phone Number
}

Donor "1   " - "   *" Donation : makes a >

@enduml