@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Register a Donor

autonumber

actor Donor
participant ":RegisterDonorUI" as ui
participant ":RegisterDonorController" as ctrl
participant Repositories
participant "donorRepo : DonorRepository" as donorRepo

activate Donor

    Donor -> ui : starts the process of registering a new Donor
    activate ui
        ui -> ctrl** : create()
        ui -> ctrl : registerDonor()
        activate ctrl
            ctrl -> Repositories : getDonorRepository()
            activate Repositories
                Repositories -> Repositories : donorRepository()
                Repositories-->ctrl : donorRepo
            deactivate Repositories
        deactivate ctrl
            ui --> Donor : requests data (provided data*)
            Donor -> ui : fills requested data (provided data*)
        activate ctrl
            ui -> ctrl : createDonor(provided data*)
            activate donorRepo
                donorRepo -> donorRepo : localValidation(provided data*)
                donorRepo --> donorRepo : donor
            deactivate donorRepo
            ctrl --> ui : success
        deactivate ctrl
    deactivate ui
deactivate Donor

note left of "donorRepo : DonorRepository"
    *Provided data*
    - First name
    - Last name
    - Phone number
    - Email address
    - Address (Street name, postal code, city and country)
    - NIF
    - Nacionality
    - Bank account informations (Bank name, IBAN, Bank account holder name)
end note

@enduml