@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title US026 - Administrator validates the request for service-related cost support

class CostSupportRequest {
    Id
    Date Request
    Date of Service
    Value
    Description
    Status
    CostSupportType
}

class Service {
    Id
    Name
    Category
}

class ServiceProvider {
    Id
    First Name
    Last Name
    License Number
    Address
    Phone Number
    Email
    Category
}

class Administrator {
    Id
    Name
}

ServiceProvider "1   " - "   *" Service : performs a >
Service "1   " - "   1" CostSupportRequest : generates a >
Administrator "1  " -- " *  " CostSupportRequest : validates a >

@enduml