@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Visualize a list of services available

autonumber

actor Refugee
participant ":ServiceListUI" as ui
participant ":ServiceListController" as ctrl
participant Repositories
participant "serviceRepo : ServiceRepository" as serviceRepo

activate Refugee

    Refugee -> ui : access the system to visualize the list of services available
    activate ui
        ui -> ctrl** : create()
        ui -> ctrl : displayServiceList()
        activate ctrl
            ctrl -> Repositories : getServiceRepository()
            activate Repositories
                Repositories -> Repositories : serviceRepository()
                Repositories-->ctrl : serviceRepo
            deactivate Repositories
            ctrl --> ui : presents the list of services in alphabetical order
        deactivate ctrl
            ui --> Refugee : shows the list of services without needing to log in
            ui --> Refugee : provides a search bar for inputting keywords
            Refugee -> ui : inputs keywords into the search bar
        activate ctrl
            ui -> ctrl : searchServices(keywords)
            activate serviceRepo
                serviceRepo -> serviceRepo : searchByKeywords(keywords)
                serviceRepo --> serviceRepo : services
            deactivate serviceRepo
            ctrl --> ui : provides real-time results as the refugee adjusts filters
            ui --> Refugee : shows dynamic results
        deactivate ctrl
    deactivate ui
deactivate Refugee

@enduml