@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US012 - System Sequence Diagram (SSD)

autonumber

actor "Service Provider" as SP
participant ":System" as System

activate SP
    SP -> System : starts the process of register a service
    activate System
        System --> SP :displays a list of service provider categories
    deactivate System
    SP -> System: selects a service provider category

    activate System
        System --> SP : displays a list of services of the chosen category
    deactivate System
    SP -> System : selects one or more services and confirm

    activate System
        System --> SP : system records the information
   deactivate System
deactivate SP
@enduml