@startuml
'https://plantuml.com/sequence-diagram

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Register a Professional on the application (SSD)

autonumber

actor Professional
participant ":System" as System

activate Professional
    Professional -> System : starts the registration process
    activate System
        System --> Professional : shows the attributes used to describe the professional
        note right of System
                             Attributes to provide:
                             - First name
                             - Last name
                             - Birth date
                             - Gender
                             - Phone number
                             - Email address
                             - Address (Street name, postal code, city, country)
                             - NIF
                             - Nationality
                             - Native language
                             - Other languages
                             - License Number
                             - Profession
                             - Category
                             - Bank account informations (Bank name, IBAN, Bank account holder name)
        end note
    deactivate System

    Professional -> System : fills the requested data
    activate System
        System --> Professional : validates and asks for confirmation
    deactivate System

    Professional -> System : confirms
    activate System
        System --> Professional : records the information and notifies the success of the operation
    deactivate System
deactivate Professional
@enduml