@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Register a Professional on the application

autonumber

actor Professional
participant ":RegisterProfessionalUI" as ui
participant ":RegisterProfessionalController" as ctrl
participant Repositories
participant "professionalRepo : ProfessionalRepository" as professionalRepo

activate Professional

    Professional -> ui : starts the process of registering a new Professional
    activate ui
        ui -> ctrl** : create()
        ui -> ctrl : registerProfessional()
        activate ctrl
            ctrl -> Repositories : getRefugeeRepository()
            activate Repositories
                Repositories -> Repositories : professionalRepository()
                Repositories-->ctrl : professionalRepo
            deactivate Repositories
        deactivate ctrl
            ui --> Professional : requests data (provided data*)
            Professional -> ui : fills requested data (provided data*)
        activate ctrl
            ui -> ctrl : createProfessional(provided data*)
            activate professionalRepo
                professionalRepo -> professionalRepo : localValidation(provided data*)
                professionalRepo --> professionalRepo : professional
            deactivate professionalRepo
            ctrl --> ui : success
        deactivate ctrl
    deactivate ui
deactivate Professional

note left of "professionalRepo : ProfessionalRepository"
    *Provided data*
    - First name
    - Last name
    - Birth date
    - Gender
    - Phone number
    - Email address
    - Address (Street name, postal code, city and country)
    - NIF
    - Nacionality
    - Native language
    - Other languages
    - License Number
    - Profession
    - Category
    - Bank account informations (Bank name, IBAN, Bank account holder name)
end note

@enduml