@startuml
'https://plantuml.com/sequence-diagram

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US04 - Refugee searches for a service by location and type of service

autonumber

actor Refugee
participant ":System" as System

activate Refugee
    Refugee -> System : starts the process of searching for a specific service on a specific location
    activate System
        System --> Refugee : requests data (service/name of service provider and location)
    deactivate System
    Refugee -> System : types the service or the name of service provider and fills the requested location
    activate System
        System --> Refugee : shows a list of services providers, ordered by geographic proximity, validates and asks for confirmation
    deactivate System
    Refugee -> System : selects a service provider
    activate System
        System --> Refugee: takes the user to the scheduling page
    deactivate System
deactivate Refugee
@enduml