@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) US015 - View previous medical information registered about the refugee

autonumber

actor Professional
participant ":System" as System

activate Professional
    Professional -> System : starts the process of requesting a previous medical information registered about the refugee report.
    activate System
        System --> Professional : asks for the options to filter and sort reviews based on different criteria, such as date, rating, or type of service of the reviews the professional wants to see.
    deactivate System

    Professional -> System : fills different criteria available.

    activate System
        System --> Professional : validates and asks for confirmation
    deactivate System

    Professional -> System : confirms
    activate System
        System --> Professional : records the information and notifies the success of the operation
    deactivate System
deactivate Professional

@enduml